config/routes.rb
Rails.application.routes.draw do


  root 'pagina#principal'
  get 'pagina/residuos'
  get 'pagina/principal'
  get "/residuos", to:"pagina#residuos", as:"pagina"
  get 'pagina/mecanica'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pagina_controller.rb
class PaginaController < ApplicationController
  def principal
  end
  
  def residuos
  	
  end
  def mecanica
  	
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pagina_helper.rb
module PaginaHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JesicaGómez</title>
  
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-inverse navbar">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed boton" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<strong><%= link_to "JG", pagina_principal_url %></strong>
			</div>
			<div id="navbar" class="collapse navbar-collapse" aria-expanded= "false">
				<ul class="nav navbar-nav">
					<li><%= link_to "Residuos peligrosos", pagina_residuos_url%> <span class="glyphicon glyphicon-fire"></span></li>
					<li><%= link_to "Fisica mecánica", pagina_mecanica_url%><span class="glyphicon glyphicon-send"></span> </li>
				</ul>
				<form class="navbar-form navbar-right" >
					<div class="form-group">
						<input type="text" class="form-control" placeholder="Buscar">
					</div>
					<button type="submit" class="btn btn-danger">Enviar</button>
				</form>
			</div><!--/.nav-collapse -->
		</div>
	</nav>
    <%= yield %>
  </body>
</html>

app/views/pagina/mecanica.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Mecanica</title>
</head>
<body>
<div class="row">
		<a href="#"> CONCEPTOS PREVIOS </a>
		<br>
		<a href="#"> DEFINICIONES </a>
		<br>
		<a href="#"> ECUACIONES BÁSICAS</a>
	</div>


	<H1><CENTER> <STRONG> <font color="red">FÍSICA MECÁNICA</font></STRONG></CENTER></H1>
	<br>
	<H2><CENTER>¿QUÈ ES?</CENTER></H2>
	<br>
	<center><article> <p align="CENTER">Es la rama de la física que estudia el movimiento y estado de los cuerpos. Dado que los fenómenos que estudia son físicos está relacionada con las matemáticas. Sin embargo, también puede relacionarse con la ingeniería, en un modo menos riguroso. Ambos puntos de vista se justifican parcialmente ya que, si bien la mecánica es la base para la mayoría de las ciencias de la ingeniería clásica, no tiene un carácter tan empírico como éstas y, en cambio, por su rigor y razonamiento deductivo, se parece más a la matemática. Describe y predice las condiciones de reposo y movimiento debido a la accion de las fuerzas.</p></article></center>
	<h2><center>La física mecánica esta formada por :</center></h2>
</body>
</html>

app/views/pagina/principal.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Bienvenidos</title>
</head>
<body>
<h1><center>ESTA ES LA PAGíNA DE INICIO <br> 	¡BIENVENIDOS!</center></h1>

</body>
</html>

app/views/pagina/residuos.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>RESIDUOS PELIGROSOS</title>
</head>
<body>
	<div class="row Row" >
		<center ><h1>RESIDUOS PELIGROSOS</h1></center>
		<div class="col-md-offset-4 col-md-2" >
			<img src="http://i2.esmas.com/2011/01/21/171877/crece-generacion-de-desechos-peligrosos-300x350.jpg" id="img">
		</div>
		<div class="col-md-2">
			<br>
			<br>
			<center><article>Son aquellos materiales que poseen características intrínsecas, es decir, causan daño a la salúd humana y/o al ambiente</article></center>
		</div>
	</div>
	<hr>
	<div class="row">
		<section  class="col-md-3" >
			<button class="uno" ><center> <h3>¿Cuales residuos son peligroso?</h3>
				<img src="http://3.bp.blogspot.com/-keq8mcrW1Pc/U-JES4TLklI/AAAAAAAAACQ/svyx4V3eXu8/s1600/Hazardous%252520Waste.jpg" > 
			</center></button>
			
			</section>
			
			<section class="col-md-3">
				<button class="dos" ><center><h3>¿Como identificarlos?</h3>
					<img src="http://www.vbrreciclados.com/wp-content/uploads/2015/10/residuos-peligrosos.jpg" >
				</center></button>
				
			</section>
			<section class="col-md-3">
				<button class="tres" ><center><h3>¿Como tratarlos?</h3>
					<img src="http://img.formacionyestudios.com/wp-content/uploads/2010/11/gestion-de-residuos-peligrosos.jpg" >
				</center></button>
			
			</section>
			<section class="col-md-3">
				<button class="cuatro" ><center><h3>¿Como es sancionada la mala gestión de ellos?</h3>
					<img src="http://laizquierdadiario.com/IMG/arton35994.jpg" >
				</center></button>
				
			</section>
		</div>
		<div class="row">
            <div class="none one" id="one">one</div>
			<div class="none dos" id="two">two</div>
			<div class="none tres" id="three">three</div>
			<div class="none cuatro" id="four">four</div>
		</div>
	</body>
	</html>